local:
  api_endpoint    : "http://bt-service.herokuapp.com/"
  web_port        : 8888

development:
  api_endpoint    : "http://bt-service.herokuapp.com/"
  web_port        : 8888

test:
  api_endpoint    : "http://bt-service.herokuapp.com/"
  web_port        : 8888

automation:
  api_endpoint    : "http://bt-service.herokuapp.com/"
  web_port        : 8889

production:
